pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                sh 'ansible-playbook playbooks/ping/ping.yml --syntax-check'
            }
        }

        stage('Deploy') {
            steps {
                sh 'ansible-playbook playbooks/ping/ping.yml'
            }
        }
    }
}