---
- name: "Ping Inventory Hosts"
  hosts: "{{ my_host | default('MIRROR-SERVERS') }}"
  gather_facts: false

  vars:
    user_state: "present"

  tasks:
    - name: Ping Remote Hosts
      ansible.builtin.debug:
        msg: "Ping {{ inventory_hostname }}"

    - name: Display Hosts
      ansible.builtin.ping:

...
