---
- name: Ansible Vault playbook.yml
  hosts: "{{ my_host | default('rhel-server1,rhel-server3') }}"
  gather_facts: false

  vars:
    user_state: "present"

  tasks:
    - name: Lookup File
      ansible.builtin.debug:
        msg: "Ping {{ inventory_hostname }}"

    - name: Ping Host
      ansible.builtin.ping:

...
